import './globals.css'

export const metadata = {
  title: 'KnowYourCharacter',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className=' bg-black'>{children}</body>
    </html>
  )
}
